---
name: Sync with upstream
on:
  schedule:
    - cron: 50 * * * *
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Repo
        run: gh repo sync ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
